namespace: kepler

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: kepler_model_server
  newName: quay.io/sustainable_computing_io/kepler_model_server
  newTag: v0.6

patchesStrategicMerge:
- ./patch/patch-model-server.yaml
resources:
- ../kepler
- ../server
