apiVersion: v1
kind: PersistentVolume
metadata:
  name: kepler-model-server-pv
  labels:
    type: local
    app.kubernetes.io/component: kepler-model-server-pv
    app.kubernetes.io/name: kepler-model-server-pv
spec:
  storageClassName: default
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kepler-model-server-pvc
  namespace: monitoring
spec:
  storageClassName: default
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kepler-model-server
  namespace: monitoring
  labels:
    app.kubernetes.io/component: model-server
    app.kubernetes.io/name: kepler-model-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: model-server
      app.kubernetes.io/name: kepler-model-server
  template:
    metadata:
      labels:
        app.kubernetes.io/component: model-server
        app.kubernetes.io/name: kepler-model-server
    spec:
      volumes:
      - name: models
        persistentVolumeClaim:
          claimName: kepler-model-server-pvc
      containers:
      - name: kepler-model-server
        image: quay.io/sustainable_computing_io/kepler_model_server:latest
        ports:
        - containerPort: 8100
        volumeMounts:
          - name: models
            mountPath: /models
      - name: kepler-model-trainer
        image: quay.io/sustainable_computing_io/kepler_model_server:latest
        command: ["python3.8",  "energy_scheduler.py"]
        env:
        - name: PROMETHEUS_ENDPOINT
          value: "http://prometheus-k8s:9090/api/v1/query"
        volumeMounts:
          - name: models
            mountPath: /models
---
kind: Service
apiVersion: v1
metadata:
  name: kepler-model-server
  namespace: monitoring
  labels:
    app.kubernetes.io/component: model-server
    app.kubernetes.io/name: kepler-model-server
spec:
  clusterIP: None
  selector:
    app.kubernetes.io/component: model-server
    app.kubernetes.io/name: kepler-model-server
  ports:
  - name: http
    port: 8100
    targetPort: http
