spec:
  template:
    spec:
      containers:
      - name: online-trainer
        image: quay.io/sustainable_computing_io/kepler_model_server:latest
        imagePullPolicy: IfNotPresent
        volumeMounts:
          - name: mnt
            mountPath: /mnt
          - name: cfm
            mountPath: /etc/kepler/kepler.config
            readOnly: true
        command: [ "python3.8" ]
        args: ["-u", "src/train/online_trainer.py" ]