name: BuildPushDeployImage

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      
    - name: Build image
      run: docker build -t quay.io/sustainable_computing_io/kepler_model_server:latest server/ -f server/dockerfiles/Dockerfile
      
    - name: Login to Quay
      if: ${{ (github.repository_owner == 'sustainable-computing-io') && (github.ref == 'refs/heads/main') }}
      uses: docker/login-action@v1
      with:
          registry: quay.io/sustainable_computing_io
          username: ${{ secrets.BOT_NAME }}
          password: ${{ secrets.BOT_TOKEN }}      

    - name: Push to quay
      if: ${{ (github.repository_owner == 'sustainable-computing-io') && (github.ref == 'refs/heads/main') }}
      run: docker push quay.io/sustainable_computing_io/kepler_model_server:latest


  deploy_server_only_with_local:
    needs: build
    uses: ./.github/workflows/cluster_deploy.yml
    if: ${{ (github.repository_owner == 'sustainable-computing-io') && (github.ref == 'refs/heads/main') }}
  deploy_with_online_trainer:
    needs: build
    uses: ./.github/workflows/cluster_deploy.yml
    if: ${{ (github.repository_owner == 'sustainable-computing-io') && (github.ref == 'refs/heads/main') }}
    with:
      online_trainer: true

  deploy_server_only_with_local_dev:
    needs: build
    uses: ./.github/workflows/cluster_deploy.yml
    if: ${{ (github.repository_owner != 'sustainable-computing-io') || (github.ref != 'refs/heads/main') }}
    with:
      storage: dev
  deploy_with_online_trainer_dev:
    needs: build
    uses: ./.github/workflows/cluster_deploy.yml
    if: ${{ (github.repository_owner != 'sustainable-computing-io') || (github.ref != 'refs/heads/main') }}
    with:
      storage: dev
      online_trainer: true