name: BuildPushDeployImage

on:
  push:

env:
  IMAGE_VERSION: '0.7'
  IMAGE_REGISTRY: quay.io/sustainable_computing_io
  IMAGE_NAME: kepler_model_server

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v3
    - name: set up QEMU
      uses: docker/setup-qemu-action@v2
    - name: set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: build Kepler model server
      run: make build

    - name: Login to Quay
      if: ${{ (github.repository_owner == 'sustainable-computing-io') && (github.ref == 'refs/heads/main') }}
      uses: docker/login-action@v1
      with:
          registry: quay.io/sustainable_computing_io
          username: ${{ secrets.BOT_NAME }}
          password: ${{ secrets.BOT_TOKEN }}      

    - name: Push to quay
      if: ${{ (github.repository_owner == 'sustainable-computing-io') && (github.ref == 'refs/heads/main') }}
      run: make push


    - name: Tag latest and push to quay
      if: ${{ (github.repository_owner == 'sustainable-computing-io') && (github.ref == 'refs/heads/main') }}
      run: |
        docker tag ${{env.IMAGE_REGISTRY}}/${{env.IMAGE_NAME}}:v${{env.IMAGE_VERSION}} ${{env.IMAGE_REGISTRY}}/${{env.IMAGE_NAME}}:latest
        docker push ${{env.IMAGE_REGISTRY}}/${{env.IMAGE_NAME}}:v${{env.IMAGE_VERSION}}
        docker push ${{env.IMAGE_REGISTRY}}/${{env.IMAGE_NAME}}:latest