name: Makefile and Push

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Install dependencies
      run: docker build -t quay.io/sustainable_computing_io/kepler_model_server:latest server/ -f server/Dockerfile
      
    - name: Login to Quay
      uses: docker/login-action@v1
      with:
          registry: quay.io/sustainable_computing_io
          username: ${{ secrets.BOT_NAME }}
          password: ${{ secrets.BOT_TOKEN }}      

    - name: push to quay
      run: podman push quay.io/sustainable_computing_io/kepler_model_server:latest
