name: Build and push base image

on:
  push:
    branches:
      - main
    paths:
      - server/dockerfiles/requirements.txt
      - server/dockerfiles/Dockerfile.base

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      
    - name: Build image
      run: docker build -t quay.io/sustainable_computing_io/kepler_model_server_base:latest dockerfiles -f dockerfiles/Dockerfile.base
      
    - name: Login to Quay
      uses: docker/login-action@v1
      with:
          registry: quay.io/sustainable_computing_io
          username: ${{ secrets.BOT_NAME }}
          password: ${{ secrets.BOT_TOKEN }}      

    - name: Push to quay
      run: docker push quay.io/sustainable_computing_io/kepler_model_server_base:latest
