name: Build and push base image

on:
  push:
    branches:
      - main
    paths:
      - dockerfiles/requirements.txt
      - dockerfiles/Dockerfile.base
      - .github/workflows/docker-base-image.yml

env:
  IMAGE_VERSION: '0.7'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      
    - name: Build image
      run: |
        docker build -t quay.io/sustainable_computing_io/kepler_model_server_base:v${{env.IMAGE_VERSION}} dockerfiles -f dockerfiles/Dockerfile.base
      
    - name: Login to Quay
      if: ${{ (github.repository_owner == 'sustainable-computing-io') && (github.ref == 'refs/heads/main') }}
      uses: docker/login-action@v3
      with:
          registry: quay.io/sustainable_computing_io
          username: ${{ secrets.BOT_NAME }}
          password: ${{ secrets.BOT_TOKEN }}      

    - name: Push to quay
      if: ${{ (github.repository_owner == 'sustainable-computing-io') && (github.ref == 'refs/heads/main') }}
      run: |
        docker push quay.io/sustainable_computing_io/kepler_model_server_base:v${{env.IMAGE_VERSION}}
