name: Train Power Model on Self-hosted Runner

on:
  push:
    branches:
      - v*-release

jobs:
  check-secret:
    runs-on: ubuntu-latest

    outputs:
      available: ${{ steps.check-secret.outputs.available }}

    steps:
      - name: Check Secret
        id: check-secret
        env:
          SECRET: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
        run: |
          if [ "$SECRET" == "" ]; then
              echo "available=false" >> "$GITHUB_OUTPUT"
          else
              echo "available=true" >> "$GITHUB_OUTPUT"
          fi

  train-model:
    if: ${{ needs.check-secret.outputs.available == 'true' }} 
    strategy:
      matrix:
        instance_type: [i3.metal, c6i.metal]
      max-parallel: 1

    uses: ./.github/workflows/train-model-self-hosted.yml
    with:
      instance_type: ${{ matrix.instance_type }}
      ami_id: 'ami-0e4d0bb9670ea8db0'
      github_repo: ${{ github.repository }}
    secrets:
      self_hosted_github_token: ${{ secrets.GH_SELF_HOSTED_RUNNER_TOKEN }}
      aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      security_group_id: ${{ secrets.AWS_SECURITY_GROUP_ID }}
      aws_region: ${{ secrets.AWS_REGION }}
